### ISSUE TITLE
Protection of API Key

### ISSUE THREAD

**Issue by stevespringett** [gemnasium/gemnasium-maven-plugin#1]
How would I go about using the Maven plugin without having to manually invoke it. 

I want Travis CI to be able to call plugin, but in order to do that, the API key would need to be checked into version control, which obviously would be a bad thing. How would Travis CI users use this Maven plugin in a secure way?

**Comment by gravis** [comment]
You can safely put your api in your CI environment (not in clear text obviously).
Most CI around there can handle that for you. If you're using Travis, you should encrypt your key: https://docs.travis-ci.com/user/encryption-keys/
